### ISSUE TITLE
Catalog actions (3 dots)

### ISSUE THREAD

**Issue by KatrinN87** [cardstack/boxel-archive-2021#162]
All actions for the catalogs should be stacked under the 3 dots ...

- "Delete"
- "Duplicate"
- "Add to collection"
       - Shortcut: "Add to Batch F"

<img width="635" alt="Bildschirmfoto 2020-06-05 um 12 33 15" src="https://user-images.githubusercontent.com/66374655/83866865-c1318580-a728-11ea-9026-28276c76fe69.png">

**Comment by burieberry** [comment]
@KatrinN87 Do you mean "Delete" and "Duplicate" go in the menu under the three dots button, and "Add to Batch F" goes in the menu under "Add to collection" button?

Does this look right for the more actions menu?

<img width="618" alt="more-actions-menu" src="https://user-images.githubusercontent.com/16160806/84078875-a28cf200-a9a7-11ea-8c96-468179bc3c36.png">

**Comment by KatrinN87** [comment]
The way I understood it, we only want 1 "..." menu with all the actions (Delete + Duplicate + Add to Collection), and then it works like a hierarchy – so once you have selected "Add to Collection", you can select the catalog you want. Is that right @christse?
