### ISSUE TITLE
Get "Add artist" feature to work (Musical Work)

### ISSUE THREAD

**Issue by KatrinN87** [cardstack/boxel-archive-2021#180]
<img width="772" alt="Bildschirmfoto 2020-06-24 um 14 50 28" src="https://user-images.githubusercontent.com/66374655/85841635-ae95f380-b79e-11ea-9639-349a57222fc3.png">

**Comment by alexspeller** [comment]
Addressed by #196

**Comment by burieberry** [comment]
I'll do the styling for this #131
