### ISSUE TITLE
Change status for threads in queue

### ISSUE THREAD

**Issue by KatrinN87** [cardstack/boxel-archive-2021#185]
The recent threads that are part of the "Rights Transfer, CRD Records" project shouldn't be "under review". It makes more sense for those to be "completed" by now, since we're already at the point of transferring the catalog.

Similarly, not all of CRD's threads would be "under review". At least the "To Dos" should be "complete"; and the "Radio interview" should be "Data requested" (assuming that a reporter wants some catalog data from Steve).

![Bildschirmfoto 2020-06-23 um 16 33 22](https://user-images.githubusercontent.com/66374655/85839427-38dc5880-b79b-11ea-8b13-328f351e11f5.png)
![Bildschirmfoto 2020-06-23 um 16 49 11](https://user-images.githubusercontent.com/66374655/85839458-409bfd00-b79b-11ea-8ff6-a11dbd552aa0.png)

**Comment by burieberry** [comment]
@KatrinN87  We don't have a "data requested" status. Should there be one and what % completion level is it?

I put it in 20% complete for now: 

### Steve's queue:
![185-crd](https://user-images.githubusercontent.com/16160806/85882062-99c05c80-b7ac-11ea-9b62-04fe889f425f.png)


### Lisa's queue:
![185-bunny](https://user-images.githubusercontent.com/16160806/85881827-42ba8780-b7ac-11ea-91f4-ed60b2498c6a.png)
