### ISSUE TITLE
Change catalog name + cover art for transfer (ember.s3)

### ISSUE THREAD

**Issue by KatrinN87** [cardstack/boxel-archive-2021#188]
For the blockchain part:
It's inconsistent to use "Batch F" with "73 masters" and "Sarah Vaughan" as artist (doesn't match with the rest of our scenario). 

**1) Let's rename that catalog "Batch G"** with the description "Transfer to CRD Records", so we can act like this is an entirely new transfer. 

![Bildschirmfoto 2020-06-23 um 17 18 31](https://user-images.githubusercontent.com/66374655/85839968-0717c180-b79c-11ea-89db-f2db4dfbda80.png)

**2) It also needs to have different cover art** than Batch F. I'll attach some pictures here, but you can also find them in the folder with all the other cover art (files titled "BatchG"): https://drive.google.com/drive/folders/1NSLUILKYGn6T5Nb9ozAvQeI4ZEynLLlT

![BatchG-2](https://user-images.githubusercontent.com/66374655/85841020-c456e900-b79d-11ea-97a2-789fd303d2ad.jpg)
![BatchG-3](https://user-images.githubusercontent.com/66374655/85841084-db95d680-b79d-11ea-98cc-d6b2929d9ef7.jpg)
![BatchG-4](https://user-images.githubusercontent.com/66374655/85841026-c620ac80-b79d-11ea-88ab-9724ee609b37.jpg)
![BatchG-5](https://user-images.githubusercontent.com/66374655/85841028-c6b94300-b79d-11ea-873f-94856839a5ea.jpg)
![BatchG-1](https://user-images.githubusercontent.com/66374655/85840999-bd2fdb00-b79d-11ea-98c3-231f7d0e011d.jpg)

**Comment by burieberry** [comment]
@KatrinN87 Should we do these changes on the github demo link as well? (https://cardstack.github.io/boxel/#/bunny_records/agreements)

**Comment by KatrinN87** [comment]
> @KatrinN87 Should we do these changes on the github demo link as well? (https://cardstack.github.io/boxel/#/bunny_records/agreements)

No, let's keep that as is. I need the demo link to show the Batch F transfer in the video.
