### ISSUE TITLE
Card transitions: edit fields in layout mode

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/boxel-archive-2021#61]
This is a placeholder for in-place editing exploration for different types of fields. 

We need to edit following ui component types:
- [ ] text field
- [ ] long text (text area?)
- [ ] dropdown
- [ ] date

Motion study to be added

**Comment by cmgardella** [comment]
Uploading zip of motion examples.  Included example of pop over editing for date and time, unsure if this is what you meant by "dropdown" example.
[edit fields in layout mode.zip](https://github.com/cardstack/boxel/files/3640420/edit.fields.in.layout.mode.zip)

**Comment by cmgardella** [comment]
Please note that Blue selection marquee around card dims to 50% opacity when a field within card is selected/in focus (this will also have a blue marquee but at 100% opacity.)  

I think this is potentially confusing as a user should only be able to have one object in focus at a time.  This is specifically a Chris request so we'll see how it works when implemented.
