### ISSUE TITLE
Card transitions: edit fields in form mode

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/boxel-archive-2021#62]
This is placeholder for form editing mode. Mostly this is standard editing, so this might not need an explainer video - I'll leave it to @cmgardella to decide

**Comment by cmgardella** [comment]
Attaching motion example of field editing in form mode.  This is mostly to illustrate change in focus from general card to individual field.

[Uploading Edit_Fields_FormMode.mp4.zip…]()
