### ISSUE TITLE
Card transitions: pop and pack (crop picture)

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/boxel-archive-2021#63]
For certain types of ui components (e.g. embedded images) user should be able to open advanced editor, or controlling card (if field contains a card) and perform additional configuration or other related actions. Example of this is cropping the image. 
We use pop-and-pack pattern to open the attached image in a modal overlay (new plane), crop it, and close. The card should reflect changes made in the modal.

**Comment by cmgardella** [comment]
Attaching example of pop and pack field in form edit mode.  

UPDATED Sep24
Updated video with smoother animation - I'm noticing Adobe XD runs smoother/choppier depending on what monitor I'm using (seems to stutter when hooked up to the LGs in the office.)
Probably related to native resolution of monitor, for whatever reason it is running much smoother on my  home monitor.

[PopAndPack_FormMode_3.mp4.zip](https://github.com/cardstack/boxel/files/3648734/PopAndPack_FormMode_3.mp4.zip)
