### ISSUE TITLE
Card transitions: switching between form and schema edit modes

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/boxel-archive-2021#64]
Switching between different types of Edit view is available in the extended menu (horizontal ellipsis).

In schema edit mode the content of the card is not editable and is displayed as a placeholder. In the right edge user can control the type of the field, and its properties. 

Please refer to motion study and design file for details

**Comment by cmgardella** [comment]
Posting motion study of transition from Form to Schema mode.  Please note that Schema view details and UI are still in the process of being finalized.  
[Transitions_FormToSchema.mp4.zip](https://github.com/cardstack/boxel/files/3643898/Transitions_FormToSchema.mp4.zip)

**Comment by cmgardella** [comment]
Posting example of transition from form to schema mode.  Please note that as of Sep 23 Chris had a slightly different direction he wanted implemented for Schema mode. Will replace motion comp when the latest treatment is approved.

[Uploading Transitions_FormToSchema.mp4.zip…]()
