### ISSUE TITLE
Card transitions: switching between layout and schema edit mode

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/boxel-archive-2021#65]
This is mostly similar to #64 except we will need to display components in different modes. We don't need to animate the ui component transitions, just fade out/in. 

Switching between different types of Edit view is available in the extended menu (horizontal ellipsis).

In schema edit mode the content of the card is not editable and is displayed as a placeholder. In the right edge user can control the type of the field, and its properties.

Please refer to motion study and design file for details

**Comment by cmgardella** [comment]
Posting motion example for transition from Layout to Schema mode:

[Transitions_LayoutToSchema.mp4.zip](https://github.com/cardstack/boxel/files/3644178/Transitions_LayoutToSchema.mp4.zip)

**Comment by cmgardella** [comment]
Please note that as of Sep 23 Chris had a slightly different direction he wanted implemented for Schema mode.  Will replace motion comp when the latest treatment is approved.
