### ISSUE TITLE
Card: Switching between view and edit mode

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/boxel-archive-2021#8]
Edit mode has 3 sub-modes: 
- Content editing
- Design editing
- Schema editing

When card switches from view and edit mode, by default it is switching to Content editing mode. 

### Content editing mode
In this mode user edits card's contents inline. Card is elevated into the tools plain. Edges are not visible(?). Tools allow for selecting/adding objects and basic formatting. 

### Design editing mode
In this mode card is elevated into the edges plain. Edges slide in from the respective sides (only those that are required at the moment). Right edge displays properties and metadata of the selected field. 

### Schema editing mode
In this mode user is presented with the list of fields and their properties. Card is elevated into the edges plain. User can modify schema (TBD)

**Comment by bagby** [comment]
@dnaidionov I split this out into 3 issues #10, #11, and #12, they can be worked on separately.
