### ISSUE TITLE
Add right edge

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/boxel-archive-2021#87]
Right edge is also contained within a boxel. It displays properties and structure of the selected card. 

Right edge should be hidden in view mode, and displayed in the edit modes (layout/edit/schema)

In most general case Right edge contains 2 tabs - `Properties` and `Structure`. 

When no object on a card is selected, Properties tab displays properties of the card itself. It consists of following sections: 
- Adopt
- Facade (future implementation, hidden now)
- Metadata
In different modes additional sections may be displayed 
When a field is selected on a card, Properties will display the properties of the selected field. Contents of the properties panel for the same object depends on the mode. 

Structure tab shows hierarchical structure of fields in the card. Complete functionality TBD.

![image](https://user-images.githubusercontent.com/1836666/66955678-dd18d780-f030-11e9-8c3f-5fc9acc297bc.png)

XD file: https://xd.adobe.com/spec/03e766cd-959e-45b5-7820-e594f7f17ff6-75d6/
pwd: Cardstack4TW

**Comment by robustdj** [comment]
@dnaidionov As I mentioned in standup, wiring up the `Required` checkbox will require a bit of refactoring in the way that fields and constraints work together. When you file a ticket, you can ask @habdelra for the details.
![Screen Shot 2019-10-28 at 7 26 22 AM](https://user-images.githubusercontent.com/118005/67865852-42ff6780-fae5-11e9-80bb-6bb5f3c4d898.png)
