### ISSUE TITLE
Card: Syndication view

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/boxel-archive-2021#9]
In syndication view card displays previews of all defined formats. Preview is scaled down to fit into the display area of the containing boxel (by default - container of isolated card). 
By default card has only embedded and isolated views. But developers can define additional templates for different cases - e.g. for embedding into specific 3rd party website, or displaying as a thumbnail. 
In addition it will display previews of how card will look as generated social media post (FB, Twitter, Instagram, etc). 
Syndication view is entered when user selects "Preview". 
In preview mode we display a list of defined templates/views at the top. As user scrolls sideways from one view to another, the view in focus is highlighted in that list. The nearest to the center of the screen view is snapped to center. This is done so that it is easier to scale and isolate individual previews when exiting preview mode or further isolating preview. 
When user clicks on individual view in syndication mode we elevate it to higher plain, center it and display at 100% scale. The original plain with its content is dimmed. User is not able to interact with the card in this view. The only available option is return back to syndication view. 

Illustrations TBD

**Comment by burieberry** [comment]
Breaking up this ticket and starting with first part #13
